import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 1. 导入 Script 组件
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* --- Google Analytics 开始 --- */}
        {/* 加载外部脚本 */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-YG4VJ87GL1"
          strategy="afterInteractive"
        />
        {/* 执行初始化脚本 */}
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-YG4VJ87GL1');
          `}
        </Script>
        {/* --- Google Analytics 结束 --- */}
      </body>
    </html>
  );
}